### ISSUE TITLE
Rebase to v1.10.18 of root geth

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipfs-ethdb#34]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] v3 release that uses the new v1.10.18 release of geth (off of https://github.com/vulcanize/ipfs-ethdb/tree/release-v3.0.1)
- [x] v4 release that uses the new v1.10.18 release of geth (off of https://github.com/vulcanize/ipfs-ethdb/tree/release-v4.0.0-alpha)

During this upgrade, we will need to make changes to acomodate the changes made to the ethdb interace: ancient interface was broken (renaming of constituent interfaces) and extended in: https://github.com/ethereum/go-ethereum/pull/24684

**Comment by abdulrabbani00** [comment]
Final:

* V3 - https://github.com/vulcanize/ipfs-ethdb/releases/tag/v3.0.3
* V4 - https://github.com/vulcanize/ipfs-ethdb/releases/tag/v4.0.1-alpha
